controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_wine:
    path: /wines
    controller: App\Controller\WineController::index

app_cart_add:
    path: /cart/add
    controller: App\Controller\CartController::add

app_cart:
    path: /cart
    controller: App\Controller\CartController::index

app_cart_remove:
    path: /cart/remove/{id}
    controller: App\Controller\CartController::remove

app_cart_clear:
    path: /cart/clear
    controller: App\Controller\CartController::clear

app_checkout:
    path: /checkout
    controller: App\Controller\CheckoutController::index

app_cart_update:
    path: /cart/update
    controller: App\Controller\CartController::update
    methods: [POST]